# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\asd\Desktop\py\hc\duihuan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_duihuan(object):
    def setupUi(self, duihuan):
        duihuan.setObjectName("duihuan")
        duihuan.resize(290, 141)
        duihuan.setAutoFillBackground(False)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(duihuan)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 10, 271, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.gridLayoutWidget_2)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(duihuan)
        QtCore.QMetaObject.connectSlotsByName(duihuan)

    def retranslateUi(self, duihuan):
        _translate = QtCore.QCoreApplication.translate
        duihuan.setWindowTitle(_translate("duihuan", "Form"))
        self.label.setText(_translate("duihuan", "兑换码"))
