# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\asd\Desktop\py\hc\error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msg(object):
    def setupUi(self, Form, msg=""):
        Form.setObjectName("Form")
        Form.resize(237, 90)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 40, 111, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form,msg)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form, msg=""):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", msg))
