# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'announcement.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_announcement(object):
    def setupUi(self, announcement):
        announcement.setObjectName("announcement")
        announcement.resize(530, 602)
        self.gridLayout = QtWidgets.QGridLayout(announcement)
        self.gridLayout.setObjectName("gridLayout")
        self.fontComboBox = QtWidgets.QFontComboBox(announcement)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout.addWidget(self.fontComboBox, 1, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(announcement)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(announcement)
        self.textBrowser.setAlignment(QtCore.Qt.AlignCenter)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 2)

        self.retranslateUi(announcement)
        QtCore.QMetaObject.connectSlotsByName(announcement)

    def retranslateUi(self, announcement):
        _translate = QtCore.QCoreApplication.translate
        announcement.setWindowTitle(_translate("announcement", "Form"))
