# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\asd\Desktop\py\hc\wuyong\update.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_update(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(331, 141)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 151, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 70, 71, 21))
        self.label_3.setObjectName("label_3")
        self.myv = QtWidgets.QLabel(Form)
        self.myv.setGeometry(QtCore.QRect(170, 22, 101, 20))
        self.myv.setObjectName("myv")
        self.newv = QtWidgets.QLabel(Form)
        self.newv.setGeometry(QtCore.QRect(170, 70, 101, 20))
        self.newv.setObjectName("newv")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 110, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 110, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 110, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "有新的版本！"))
        self.label_2.setText(_translate("Form", "你的版本是："))
        self.label_3.setText(_translate("Form", "最新版本是："))
        self.myv.setText(_translate("Form", "TextLabel"))
        self.newv.setText(_translate("Form", "TextLabel"))
        self.pushButton.setText(_translate("Form", "更新"))
        self.pushButton_2.setText(_translate("Form", "取消"))
        self.pushButton_3.setText(_translate("Form", "暂不提醒"))
